In [1]:
import numpy as np

### 불리언

In [2]:
a = np.arange(1,7).reshape(2,3)

In [3]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
bool_idx = (a > 2)

In [5]:
bool_idx

array([[False, False,  True],
       [ True,  True,  True]])

In [6]:
a[bool_idx]

array([3, 4, 5, 6])

### 정수인덱싱

In [9]:
a = np.arange(1,7).reshape(3,2)

In [10]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [11]:
a[[0,1,2], [0,1,0]]

array([1, 4, 5])

In [14]:
a[[0,0], [1,1]]

array([2, 2])

### reshape

In [15]:
a = np.arange(6).reshape(3,2)

In [16]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

### concatenate

In [18]:
a = np.array([[1,2], [3,4]])
b = np.array([[5,6]])

In [19]:
a

array([[1, 2],
       [3, 4]])

In [20]:
b

array([[5, 6]])

In [27]:
b.T

array([[5],
       [6]])

In [21]:
np.concatenate((a, b))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [26]:
np.concatenate((a, b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [29]:
x = np.array([[1., 2.], [3.,4.]])
y = np.array([[5., 6.], [7.,8.]])

v = np.array([9, 10])
w = np.array([11, 12])


In [30]:
v.dot(w)

219

In [31]:
np.dot(v,w)

219

In [32]:
x.dot(v)

array([29., 67.])

In [41]:
x = np.arange(1,13).reshape(4,3)
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [37]:
np.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [44]:
y = np.empty(x.shape)
y

array([[1.42116057e-311, 3.16202013e-322, 0.00000000e+000],
       [0.00000000e+000, 8.01097888e-307, 1.69176357e-052],
       [6.29661829e-066, 4.46816339e-033, 2.22893837e+180],
       [7.78968854e-071, 3.29707872e-032, 4.46881965e-062]])

In [50]:
v = np.array([1, 0,1])

In [51]:
for i in range(y.shape[0]) :
    y[i, :] =  x[i, :] + v
print(y)

[[ 2.  2.  4.]
 [ 5.  5.  7.]
 [ 8.  8. 10.]
 [11. 11. 13.]]


In [53]:
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [52]:
np.dot(x, v)

array([ 4, 10, 16, 22])

In [57]:
vv = np.tile(v, (4,1))

In [58]:
vv

array([[1, 0, 1],
       [1, 0, 1],
       [1, 0, 1],
       [1, 0, 1]])

In [60]:
x + vv

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10],
       [11, 11, 13]])

In [61]:
v

array([1, 0, 1])

In [62]:
x + v

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10],
       [11, 11, 13]])

In [63]:
v = np.array([1,2,3])
w = np.array([4,5])
x = np.array([[1,2,3], [4,5,6]])

In [64]:
x+ v

array([[2, 4, 6],
       [5, 7, 9]])

In [66]:
x.T + w

array([[ 5,  9],
       [ 6, 10],
       [ 7, 11]])

In [68]:
(x.T + w).T

array([[ 5,  6,  7],
       [ 9, 10, 11]])

In [72]:
w

array([4, 5])

In [74]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [81]:
x = np.empty((2,2))

In [82]:
x

array([[5., 6.],
       [7., 8.]])

In [90]:
x = np.ones((10, 10, 3)) 
len(x)

10

In [91]:
x = np.array([[1,2,3], [4,5,6]])
y = np.array([[7,8,9], [10,11,12]])

In [92]:
np.ravel(x)
x.ravel()
x.flatten()


array([1, 2, 3, 4, 5, 6])

In [95]:
np.concatenate((x,y), axis = 1)


array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [96]:
x = np.array([0,1,2])

In [97]:
x.repeat(2)

array([0, 0, 1, 1, 2, 2])

In [98]:
x = np.array([0,0,0,1,2,3,0,2,1,0])


In [99]:
x

array([0, 0, 0, 1, 2, 3, 0, 2, 1, 0])

In [104]:
x.tolist()

'[0, 0, 0, 1, 2, 3, 0, 2, 1, 0]'

In [112]:
np.array(list(map(int, ''.join(map(str, x)).strip('0'))))

array([1, 2, 3, 0, 2, 1])

In [113]:
x

array([0, 0, 0, 1, 2, 3, 0, 2, 1, 0])

In [117]:
x.tostring()

C:\Users\배진우\AppData\Local\Temp/ipykernel_12472/2475969892.py:1: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  x.tostring()


b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x02\x00\x00\x00\x03\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00'

C:\Users\배진우\AppData\Local\Temp/ipykernel_12472/278844791.py:1: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  np.fromstring(x.tostring().strip('0'), dtype=int)


TypeError: a bytes-like object is required, not 'str'

In [139]:
start_idx = np.where(x != 0)[0][0] 
end_idx = np.where(x != 0)[0][-1] + 1

x[start_idx : end_idx]

array([1, 2, 3, 0, 2, 1])

In [137]:
np.where(x != 0)[0][0]


3

In [144]:
'\"'

'"'