In [1]:
from sklearn.feature_extraction.text import CountVectorizer

In [2]:
text_data = ['나는 배가 고프다',
            '내일 점심 뭐먹지',
            '내일 공부 해야겠다',
            '점심 먹고 공부 해야지']


In [4]:
count_vectorizer = CountVectorizer()
count_vectorizer.fit(text_data)
print(count_vectorizer.vocabulary_)

{'나는': 2, '배가': 6, '고프다': 0, '내일': 3, '점심': 7, '뭐먹지': 5, '공부': 1, '해야겠다': 8, '먹고': 4, '해야지': 9}


In [5]:
sentence = [text_data[0]]
print(count_vectorizer.transform(sentence).toarray())

[[1 0 1 0 0 0 1 0 0 0]]


In [7]:
word2idx = count_vectorizer.vocabulary_
word2idx

{'나는': 2,
 '배가': 6,
 '고프다': 0,
 '내일': 3,
 '점심': 7,
 '뭐먹지': 5,
 '공부': 1,
 '해야겠다': 8,
 '먹고': 4,
 '해야지': 9}

In [8]:
idx2word = {v:k for (k, v) in word2idx.items()}
idx2word

{2: '나는',
 6: '배가',
 0: '고프다',
 3: '내일',
 7: '점심',
 5: '뭐먹지',
 1: '공부',
 8: '해야겠다',
 4: '먹고',
 9: '해야지'}

In [9]:
print(count_vectorizer.transform(text_data).toarray())

[[1 0 1 0 0 0 1 0 0 0]
 [0 0 0 1 0 1 0 1 0 0]
 [0 1 0 1 0 0 0 0 1 0]
 [0 1 0 0 1 0 0 1 0 1]]


In [10]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [11]:
tfidf_Vectorizer = TfidfVectorizer()
tfidf_Vectorizer.fit(text_data)
print(tfidf_Vectorizer.vocabulary_)

{'나는': 2, '배가': 6, '고프다': 0, '내일': 3, '점심': 7, '뭐먹지': 5, '공부': 1, '해야겠다': 8, '먹고': 4, '해야지': 9}


In [12]:
print(tfidf_Vectorizer.transform(text_data).toarray())

[[0.57735027 0.         0.57735027 0.         0.         0.
  0.57735027 0.         0.         0.        ]
 [0.         0.         0.         0.52640543 0.         0.66767854
  0.         0.52640543 0.         0.        ]
 [0.         0.52640543 0.         0.52640543 0.         0.
  0.         0.         0.66767854 0.        ]
 [0.         0.43779123 0.         0.         0.55528266 0.
  0.         0.43779123 0.         0.55528266]]


In [13]:
from sklearn.feature_extraction.text import HashingVectorizer

In [16]:
hash_Vectorizer = HashingVectorizer(n_features=10)
hash_Vectorizer.fit(text_data)

HashingVectorizer(n_features=10)

In [17]:
print(hash_Vectorizer.transform(text_data).toarray())

[[ 0.          0.57735027  0.          0.          0.57735027  0.
  -0.57735027  0.          0.          0.        ]
 [ 0.          1.          0.          0.          0.          0.
   0.          0.          0.          0.        ]
 [-0.57735027  0.57735027  0.          0.          0.          0.
   0.57735027  0.          0.          0.        ]
 [ 0.70710678  0.          0.          0.          0.          0.
   0.70710678  0.          0.          0.        ]]


In [20]:
import nltk
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\배진우\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\배진우\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.


True

In [21]:
from nltk.tokenize import word_tokenize

sentence = """
Natural language processing (NLP) is a subfield of computer science, information engineering, 
and artificial intelligence concerned with the interactions between computers and human (natural) languages, 
in particular how to program computers to process and analyze large amounts of natural language data.
"""

print(word_tokenize(sentence))


['Natural', 'language', 'processing', '(', 'NLP', ')', 'is', 'a', 'subfield', 'of', 'computer', 'science', ',', 'information', 'engineering', ',', 'and', 'artificial', 'intelligence', 'concerned', 'with', 'the', 'interactions', 'between', 'computers', 'and', 'human', '(', 'natural', ')', 'languages', ',', 'in', 'particular', 'how', 'to', 'program', 'computers', 'to', 'process', 'and', 'analyze', 'large', 'amounts', 'of', 'natural', 'language', 'data', '.']


In [24]:
sentence2 = 'Ilike you'
print(word_tokenize(sentence2))

['Il', 'ike', 'you']


In [25]:
import nltk
nltk.download('punkt')      # '/root/nltk_data/tokenizers'
nltk.download('averaged_perceptron_tagger')  # 형태소 분석을 위해 필요한 도구

sentence = """
Natural language processing (NLP) is a subfield of computer science, information engineering, 
and artificial intelligence concerned with the interactions between computers and human (natural) languages, 
in particular how to program computers to process and analyze large amounts of natural language data.
"""
word_tok = nltk.word_tokenize(sentence)
print(word_tok)

nltk.pos_tag(word_tok)

# 명사와 형용사만 표시한다.
sent_nnjj = [word for word, pos in nltk.pos_tag(word_tok) if pos == 'NN' or pos == 'JJ']
sent_nnjj

# bigram
bigram = [(a, b) for a, b in nltk.bigrams(sent_nnjj)]
bigram

# trigram
trigram = [(a, b, c) for a, b, c in nltk.trigrams(sent_nnjj)]
trigram

# n-gram
ngram = [(a, b, c, d) for a, b, c, d in nltk.ngrams(sent_nnjj, 4)]
ngram

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\배진우\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\배진우\AppData\Roaming\nltk_data...


['Natural', 'language', 'processing', '(', 'NLP', ')', 'is', 'a', 'subfield', 'of', 'computer', 'science', ',', 'information', 'engineering', ',', 'and', 'artificial', 'intelligence', 'concerned', 'with', 'the', 'interactions', 'between', 'computers', 'and', 'human', '(', 'natural', ')', 'languages', ',', 'in', 'particular', 'how', 'to', 'program', 'computers', 'to', 'process', 'and', 'analyze', 'large', 'amounts', 'of', 'natural', 'language', 'data', '.']


[nltk_data]   Unzipping taggers\averaged_perceptron_tagger.zip.


[('Natural', 'language', 'processing', 'subfield'),
 ('language', 'processing', 'subfield', 'computer'),
 ('processing', 'subfield', 'computer', 'science'),
 ('subfield', 'computer', 'science', 'information'),
 ('computer', 'science', 'information', 'engineering'),
 ('science', 'information', 'engineering', 'artificial'),
 ('information', 'engineering', 'artificial', 'intelligence'),
 ('engineering', 'artificial', 'intelligence', 'human'),
 ('artificial', 'intelligence', 'human', 'natural'),
 ('intelligence', 'human', 'natural', 'particular'),
 ('human', 'natural', 'particular', 'program'),
 ('natural', 'particular', 'program', 'large'),
 ('particular', 'program', 'large', 'natural'),
 ('program', 'large', 'natural', 'language')]

In [1]:
import konlpy
from konlpy.tag import Okt

In [2]:
okt= Okt()

In [3]:
text = '한글 자연어 처리는 재밌다. 이제부터 열심히 해야지 ㅎㅎㅎ'

print(okt.morphs(text))

['한글', '자연어', '처리', '는', '재밌다', '.', '이제', '부터', '열심히', '해야지', 'ㅎㅎㅎ']


In [23]:
from sklearn.feature_extraction.text import CountVectorizer
import numpy as np

In [24]:
text = ['성진과 창욱은 야구장에 갔다',
       '성진과 태균은 도서관에 갔다',
       '성진과 창욱은 공부를 좋아한다']

In [25]:
cv = CountVectorizer()

In [26]:
x = cv.fit_transform(text).toarray()
x

array([[1, 0, 0, 1, 1, 0, 1, 0],
       [1, 0, 1, 1, 0, 0, 0, 1],
       [0, 1, 0, 1, 0, 1, 1, 0]], dtype=int64)

In [27]:
x.T

array([[1, 1, 0],
       [0, 0, 1],
       [0, 1, 0],
       [1, 1, 1],
       [1, 0, 0],
       [0, 0, 1],
       [1, 0, 1],
       [0, 1, 0]], dtype=int64)

In [31]:
C = np.dot(x.T, x)
C

array([[2, 0, 1, 2, 1, 0, 1, 1],
       [0, 1, 0, 1, 0, 1, 1, 0],
       [1, 0, 1, 1, 0, 0, 0, 1],
       [2, 1, 1, 3, 1, 1, 2, 1],
       [1, 0, 0, 1, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 1, 0],
       [1, 1, 0, 2, 1, 1, 2, 0],
       [1, 0, 1, 1, 0, 0, 0, 1]], dtype=int64)